-- CREATE DATABASE IF NOT EXISTS log_parser;

CREATE TABLE IF NOT EXISTS log_item  (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    ip VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    request VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    user_agent VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS banned_ips(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    ip VARCHAR(20) NOT NULL,
    reason VARCHAR(200) NOT NULL
);